#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
FROM _BASE_NS_/fabric-baseos:_BASE_TAG_
RUN apt-get update && apt-get install -y netcat && rm -rf /var/cache/apt
RUN mkdir -p /etc/hyperledger
RUN mkdir -p $FABRIC_CA_HOME /var/hyperledger/fabric-ca-server
COPY payload/fabric-ca-client /usr/local/bin
RUN chmod +x /usr/local/bin/fabric-ca-client
COPY payload/fabric-ca-server /usr/local/bin
RUN chmod +x /usr/local/bin/fabric-ca-server

RUN groupadd --gid 1024 llsuser \
    && useradd --home-dir /home/llsuser --create-home --uid 1024 \
        --gid 1024 --shell /bin/sh --skel /dev/null llsuser
RUN chown -R llsuser:llsuser /etc/hyperledger
RUN chown -R llsuser:llsuser /var/hyperledger
RUN chown -R llsuser:llsuser /opt
USER llsuser

# Copy the same certificates that are currently hardcoded into the peers
ADD payload/fabric-ca.tar.bz2 $FABRIC_CA_HOME

EXPOSE 7054
CMD fabric-ca-server start -b admin:adminpw
